### PR TITLE
Made this package available for .net45 clients, because it is good

### PR DESCRIPTION
**Pull request by petero-dk**
I found this package and have been using it in my MVC5 projects running on .net45 and later, the code is fully compatible so it is simple a matter of creating a second dll and adding it to the nupack.

### CODE REVIEW

**Comment by petero-dk** [comment]
This is compiling just fine on vsts build server. I have never tried appveyor

**Comment by dei79** [comment]
It's because I'm using a custom build script, so it would be necessary to target the dotnet buidl with just the correct project and then you can call msbuild for the .net45 project. In addition nuget restore must be called for the .net45 as well. So can you please add the changed to the appveyor.yml (you can easily sign up for free to test everything with your fork). I'm happy to add a .net45 version in the nuget as well.

**Comment by dei79** [comment]
Thanks for your updates so the correct path in yml file must be

CoreHelpers.WindowsAzure.Storage.Table\CoreHelpers.WindowsAzure.Storage.Table.csproj

instead of just 

CoreHelpers.WindowsAzure.Storage.Table.csproj

I guess

**Comment by petero-dk** [comment]
I think the build for the projects are correct now, I dont know how the version string are generated or why they are not working now? That I did not touch.

**Comment by dei79** [comment]
Not sure why it's breaking but could be that you need to use in msbuild and dotnet build and restore also the AppVeyor variable: %APPVEYOR_BUILD_FOLDER%

**Comment by dei79** [comment]
Ah I guess you are referencing the Assembly.cs in the MSBuild Script, just a guessing. This make the Assembly.cs now compatible with msbuild but not with core anymore. The Assmebly.cs is patched with the powershell script.

**Comment by dei79** [comment]
So I recommend to different Assembly.cs files for the two different projects

**Comment by petero-dk** [comment]
Maybe, but actually it is the dotnet build that fails:
dotnet build -c Release CoreHelpers.WindowsAzure.Storage.Table\CoreHelpers.WindowsAzure.Storage.Table.csproj

Because the version string is:
1.5.43-ldymgyhx

That might be because this is a PR, and not simply the master branch.

I have both compiling just fine, here and on vsts with the same assembly.cs

**Comment by dei79** [comment]
Did you pull the change I did a couple minutes ago? I added in the appveyor.yml the information that a pull request should not increase the version number? This could be the root cause

**Comment by petero-dk** [comment]
And we have liftoff :-) but did your build process just upload the package to nuget automatically?

**Comment by dei79** [comment]
The changes are now published to NuGet as Version 1.6.45, thanks for contribution

**Comment by petero-dk** [comment]
Cool!

**Pull request merged**
