### PR TITLE
Added the possibility to automatically load related tables

### PR DESCRIPTION
**Pull request by petero-dk**
The feature will automatically infer the rowkey if naming conventions are followed, and will automatically handle lazy loaded types.

### CODE REVIEW

**Comment by petero-dk** [comment]
I am considering a way to improve performance on eagerly loaded tables. As my current implementation would result in a lot of small requests immediately after a large one. I.e for a call with 100 rows there would be 1 + 100 calls.

**Comment by petero-dk** [comment]
I have recreated the way to load eagerly loaded related tables, it is now resource efficient instead of making one query per related item.

**Comment by dei79** [comment]
I tried to understand what the use case is but could you explain me what you try to achieve with the related table attribute?

**Comment by petero-dk** [comment]
Hi @dei79 

Sure, the idea is that it makes the library close to a drop-in replacement for entity framework, actually.

Once I have set up the appropriate tables 
```
storageContext.AddAttributeMapperAndCreateTable<Models.Data.Country>();
storageContext.AddAttributeMapperAndCreateTable<Models.Data.Region>();
```

I can load a single object in my controller like this:
`var region = await _context.QueryAsync<Region>(regionPartionKey, regionRowKey, 1);`

If the models are created like this:
```
public class Region {
    public string RegionRowKey {get;set;};
    public string RegionPartitionKey {get;set;};

    public string CountryRowKey {get;set;}

    [RelatedTable("Countries", RowKey: "CountryRowKey")]
   public Country CountryObject {get;set;}
}
```

The I can reference the related object in the view just like this:
```
<dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Country.Name)
        </dd>
```

**Comment by petero-dk** [comment]
Sorry for the mess of commits above, I tried to sync the pr with your master. Does my explanation make any sense?

**Comment by petero-dk** [comment]
I will be closing this soon, but I am just cleaning up in all the feature additions and bugfixes I have lying around for this project. 

I have tried to separate all individual changes out into different branches and PRs so every change is specific and identifiable.

**Comment by dei79** [comment]
I would like to bring this change in the master but some checks are failing. Would it be ok for you to check this PR again?

**Comment by petero-dk** [comment]
Yes, don't worry about this one, I will refactor it complete into the new master after all the other merges.

**Comment by petero-dk** [comment]
Refactored to #21

**Pull request closed without merging**
